In [38]:
import pandas as pd

import scipy

In [24]:
stat1 = pd.read_csv('archive/stats1.csv')
pantic = pd.read_csv('archive/participants.csv')

model1 = pd.merge(stat1, pantic, on = 'id')

In [ ]:
model1

,id,win,item1,item2,item3,item4,item5,item6,trinket,kills,...,neutralminionskilled,ownjunglekills,enemyjunglekills,totcctimedealt,champlvl,pinksbought,wardsbought,wardsplaced,wardskilled,firstblood
0,9,0,3748,2003,3111,3053,1419,1042,3340,6,...,69,42,27,610,13,0,0,10,0,0
1,10,0,2301,3111,3190,3107,0,0,3364,0,...,1,1,0,211,14,1,0,17,3,0
2,11,0,1055,3072,3006,3031,3046,1036,3340,7,...,3,1,2,182,14,1,0,13,5,0
3,12,0,1029,3078,3156,1001,3053,0,3340,5,...,6,6,0,106,15,0,0,3,0,0
4,13,0,3020,1058,3198,3102,1052,1026,3340,2,...,4,3,1,159,15,0,0,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999994,1028377,1,1055,3142,3147,0,0,3006,3340,10,...,6,0,6,179,11,1,0,9,0,1
999995,1028378,0,1055,3006,3085,0,0,1037,3340,3,...,0,0,0,42,10,0,0,6,0,0
999996,1028379,0,3083,1001,1031,1028,0,0,3340,0,...,11,2,9,124,10,0,0,1,0,0
999997,1028380,0,3144,3111,1419,0,0,0,3340,3,...,28,17,11,450,10,0,0,5,1,0
999998,1028381,0,2301,3116,1001,2031,2055,0,3364,2,...,0,0,0,67,9,3,0,15,2,0

In [26]:
model2 = model1[['win', 'firstblood','matchid']]

model2

        win  firstblood  matchid
0         0           0       10
1         0           0       10
2         0           0       10
3         0           0       10
4         0           0       10
...     ...         ...      ...
999994    1           1   103125
999995    0           0   103125
999996    0           0   103125
999997    0           0   103125
999998    0           0   103125

[999999 rows x 3 columns]

In [34]:
model3 = model2.groupby('matchid').first()

model3

         win  firstblood
matchid
10         0           0
11         0           0
12         0           0
13         0           0
14         0           0
...      ...         ...
103121     1           1
103122     0           1
103123     1           0
103124     0           0
103125     1           0

[100000 rows x 2 columns]

In [36]:
model4 = pd.crosstab(model3['firstblood'], model3['win'])

In [39]:
scipy.stats.chi2_contingency(model4)

Chi2ContingencyResult(statistic=np.float64(422.72781980998354), pvalue=np.float64(6.218828002411944e-94), dof=1, expected_freq=array([[43518.5156, 46221.4844],
       [ 4975.4844,  5284.5156]]))

### 结论
通过卡方分析，计算结果p远小于0.001，所以我们拒绝H0假设，得出一血率与胜率呈现强相关性。